name: Esecuzione Giornaliera DailyDrive

on:
  schedule:
    # Questo comando fa girare lo script ogni giorno alle 05:00 del mattino (ora UTC)
    # Corrisponde alle 07:00 italiane (o 06:00 quando c'è l'ora solare)
    # - cron: '12 5 * * *'
    - cron: '56 2 * * *'
  workflow_dispatch: # Ti permette anche di farlo partire manualmente quando vuoi

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # 1. Scarica il codice del repository sul server di GitHub
    - name: Checkout repository
      uses: actions/checkout@v6

    # 2. Configura Node.js (visto che install.sh potrebbe richiederlo)
    - name: Configura Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
        
    # NUOVO STEP: Questo crea il file config.yaml prendendo il contenuto dai tuoi Secrets
    - name: Crea il file config.yaml
      run: |
        echo "${{ secrets.CONFIG_CONTENUTO }}" > config.yaml
        
    # 4. NUOVO: Crea il file dei token per saltare il login (Verifica il nome esatto del file generato sul PC, es. .tokens.json)
    - name: Crea il file dei token di autenticazione
      run: |
        echo '${{ secrets.SPOTIFY_TOKENS }}' > .spotify-token.json
        
    # 3. ESEGUE I COMANDI DELLE ISTRUZIONI
    - name: Installa le dipendenze
      run: |
        chmod +x install.sh
        ./install.sh
        
    # 4. Avvia lo script principale
    # Nota: Verifica nel file README del progetto se per avviarlo serve "npm start", "node index.js" o altro.
    - name: Avvia DailyDrive
      run: |
        npm start
